{
  "name": "4studio-api",
  "env": {
    "PYTHON_VERSION": "3.12.3",
    "PRODUCTION": "true"
  },
  "buildCommand": "pip install -r requirements.txt && python manage.py collectstatic --noinput",
  "startCommand": "gunicorn 4studio.wsgi:application",
  "healthCheckPath": "/api/health/",
  "envVars": [
    {
      "key": "SECRET_KEY",
      "generateValue": true
    },
    {
      "key": "WEB_CONCURRENCY",
      "value": "4"
    }
  ],
  "disk": {
    "name": "4studio-data",
    "mountPath": "/data",
    "sizeGB": 1
  }
}
